### PR TITLE
Added BGG Link icon to game toolbar

### PR DESCRIPTION
**Pull request by lehenry**
I often find myself going to the BGG page - it makes sense to have the BGG link right on the toolbar, similar to the way it is displayed on the forum thread, instead of have to scroll to the link tab and select the link there.

### CODE REVIEW

**Comment by Kaligula0** [comment]
Good point! I never thought of improving this feature (link to BGG gamepage). However, I'm not a fan of duplicating menu options, so what do you think of making the TITLE of the game link to BGG website? For now the Title is inactive, it's clearly only for display. It might get itself a function…? ;)
sketch-1590227568078

**Comment by Kaligula0** [comment]
P.S. And thanks for finding a typo in my PL translation… 😅

**Comment by lehenry** [comment]
Making the title the link would work for me, but there wouldn't be any cue for the user.

On the other end the header already has multiple menu options in the thread page, so it would be consistent across the application - which is a good UX principle.
image

**Comment by Kaligula0** [comment]
I strongly agree with you! You convinced me. ;)

**Review by ccomeaux — APPROVED** [review]

**Comment by ccomeaux** [comment]
@lehenry can you look to resolve the conflict please? I'll get it merged and released before the end of the year. Thanks!

**Comment by lehenry** [comment]
@ccomeaux conflicts resolved, ready to merge

**Review by ccomeaux — APPROVED** [review]

**Pull request merged**
