### PR TITLE
Add ability to specify negative scores

### PR DESCRIPTION
**Pull request by cincodenada**
Many games allow negative scores, and as the website seems to support them just fine, I see no reason the BGG app shouldn't allow entry of negatives.

The UI is certainly open to suggestions, I decided that instead of messing with the buttons I'd just add a +/- button to mirror the delete button, as that seemed sensical and intuitive. I also considered adding a "-" button and bumping the checkbox button down to a wide button on its own row, but figured this was less intrusive.

In doing so I also fiddled with the weights a bit and moved the left padding to the +/- button, as is logical.

I think I covered all the details in the affected helpers. I also added maybeUpdateOutput(), which encompasses a bit of code that was already duplicated twice and would have had to been a third time to handle the negative button.

### CODE REVIEW

**Comment by ccomeaux** [comment]
Thanks for the PR. I'll look over it and give you some feedback soon. Of note, you CAN enter a negative score, but you need to go to the player edit screen where you have full control of the score, even adding characters.

**Comment by cincodenada** [comment]
Aha! I didn't know that, thanks for the pointer. This just makes it easier to enter negative scores then ☺️

_Sent from my Motorola XT1635-02 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by kamal-kamalmohamed** [comment]
@ccomeaux, @cincodenada: Hey there! I've just checked out the repo and looking for a way to contribute. This PR has been open for a while. I'd be happy to review it to help merge it in. Or was it abandoned for a reason? 😄

**Comment by ccomeaux** [comment]
There's no _good_ reason it was abandoned. If I remember correctly, at the time I was thinking there was a better place for the "-" button, but I don't know what that was. I'll try to check out the branch tonight to play with it. If it looks good I will merge it.

**Comment by cincodenada** [comment]
I agree - it is a bit awkward, but it was also the least awkward I could
figure, so 🤷‍♂️

Also, I've been running a version with this patch ever since I submitted
the PR, and while I haven't entered that many negative sores, it's worked
when I have and hasn't otherwise had problems.

I'll take another pass over it as well when I get a chance this week.

**Pull request merged**
